# Generated by Django 5.2.9 on 2025-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mduheader',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
