# Generated by Django 5.2.9 on 2025-12-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0002_mduheader_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
