# Generated by Django 5.2.9 on 2025-12-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0003_changerequest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mducert',
            name='cert_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
