# Generated by Django 5.2.9 on 2026-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0004_mducert_cert_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='bulk_add_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
