# Generated by Django 5.2.9 on 2026-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0008_submitted_constraint_only'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mduchangerowaudit',
            index=models.Index(fields=['change_request', 'operation'], name='mdu_mduchan_change__39506a_idx'),
        ),
    ]
