# Generated by Django 5.2.9 on 2026-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0009_mduchangerowaudit_mdu_mduchan_change__39506a_idx'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),

    ]
