# Generated by Django 5.2.9 on 2026-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0009_mduchangerowaudit_mdu_mduchan_change__39506a_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerequest',
            old_name='primary_approver_sid',
            new_name='business_owner_sid',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='secondary_approver_sid',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='approver_ad_group',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
