# Generated by Django 5.2.9 on 2026-02-01 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0010_rename_primary_approver_sid_changerequest_business_owner_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='decided_by_sid',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='override_scope_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='override_scope_reason',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='approver_ad_group',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='MDUApproverScopeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('REGIONAL', 'Regional'), ('LOB', 'LOB'), ('DOMAIN', 'Domain')], default='GLOBAL', max_length=20)),
                ('scope_value', models.CharField(blank=True, default='', help_text='Example: GLOBAL, APAC, EMEA, NAM, OPS, CSI', max_length=120)),
                ('approver_ad_group', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_scope_rules', to='mdu.mduheader')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('header', 'scope_type', 'scope_value', 'approver_ad_group'), name='uniq_scope_rule_per_header')],
            },
        ),
    ]
