# Generated by Django 5.2.9 on 2026-02-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0011_changerequest_contributors'),
        ('mdu', '0011_changerequest_decided_by_sid_and_more'),
    ]

    operations = [
    ]
