# Generated by Django 5.2.9 on 2026-02-03

from django.db import migrations, models


def _collapse_legacy_statuses(apps, schema_editor):
    MDUHeader = apps.get_model('mdu', 'MDUHeader')

    # Collapse legacy values to the new locked set.
    # PENDING_REVIEW, REJECTED -> IN_REVIEW
    MDUHeader.objects.filter(status__in=['PENDING_REVIEW', 'REJECTED']).update(status='IN_REVIEW')


def _noop_reverse(apps, schema_editor):
    # No reverse: legacy statuses are intentionally removed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0012_merge_20260202_2042'),
    ]

    operations = [
        migrations.RunPython(_collapse_legacy_statuses, _noop_reverse),
        migrations.AlterField(
            model_name='mduheader',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Active'), ('IN_REVIEW', 'In Review'), ('RETIRED', 'Retired')],
                default='IN_REVIEW',
                max_length=20,
            ),
        ),
    ]
