# Generated by Django 5.2.9 on 2026-03-04 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0013_lock_header_lifecycle_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mduheader',
            name='ref_name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, underscores, and hyphens are allowed.', regex='^[a-zA-Z0-9_\\-]+$')]),
        ),
    ]
