# Generated by Django 5.2.9 on 2026-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdu', '0015_mduheader_certification_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mduheader',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REVIEW', 'Pre-Publish'), ('RETIRED', 'Retired')], default='IN_REVIEW', max_length=20),
        ),
    ]
